apiVersion: v1
kind: ServiceAccount
metadata:
  # namespace: staging
  name: tekton-deploy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-deploy-role
  # namespace: staging
rules:
  - apiGroups: ["*"]
    resources: ["deployments","services","pods"]
    verbs: ["create","get","update","list","watch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-deploy-rolebinding
  # namespace: staging
subjects:
  - kind: ServiceAccount
    name: tekton-deploy
    # namespace: staging
roleRef:
  kind: Role
  name: tekton-deploy-role
  apiGroup: rbac.authorization.k8s.io
